<Project>
    <PropertyGroup>
        <Version>0.0.3</Version>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <Platforms>x64</Platforms>
        <UseWindowsForms>true</UseWindowsForms>
        <UseWPF>true</UseWPF>
        <AnalysisLevel>latest-Recommended</AnalysisLevel>
        <Configurations>Release;Debug</Configurations>
        <RevitVersion Condition="'$(RevitVersion)'==''">2020</RevitVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration)=='Debug'">
        <DefineConstants>$(DefineConstants);Debug;REVIT$(RevitVersion)</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration)=='Release'">
        <DefineConstants>$(DefineConstants);Release;REVIT$(RevitVersion)</DefineConstants>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
    <!--debug action-->
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <StartAction>Program</StartAction>
        <StartProgram>C:/Program Files/Autodesk/Revit $(RevitVersion)/Revit.exe</StartProgram>
    </PropertyGroup>
    <!--TargetFramework-->
    <PropertyGroup>
        <TargetFramework Condition="$(RevitVersion) &lt;= '2024'">net48</TargetFramework>
        <TargetFramework Condition="$(RevitVersion) == '2025'">net8.0-windows</TargetFramework>
    </PropertyGroup>
    <!--packages-->
    <ItemGroup>
        <PackageReference Include="NLog" Version="6.0.7" />
    </ItemGroup>
    <!--analyser-->
    <ItemGroup>
        <PackageReference Include="Roslynator.Analyzers" Version="4.14.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.14.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.14.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>


