<Project>
  <PropertyGroup>
    <Version>0.0.1-rc.2</Version>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Configurations>Release;Debug2018;Debug2019;Debug2020;Debug2021;Debug2022;Debug2023;Debug2024;Debug2025</Configurations>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AnalysisLevel>latest-Recommended</AnalysisLevel>
    <CSharpier_LogLevel>Warning</CSharpier_LogLevel>
  </PropertyGroup>
  <!--set debug revit version and constants-->
  <PropertyGroup Condition="$(Configuration.StartsWith('Debug'))">
    <RevitVersion>$(Configuration.Replace("Debug",""))</RevitVersion>
    <DefineConstants>$(DefineConstants);Debug</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration)=='Release'">
    <DefineConstants>$(DefineConstants);Release</DefineConstants>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup>
    <RevitVersion Condition="'$(RevitVersion)'==''">2020</RevitVersion>
    <DefineConstants>$(DefineConstants);REVIT$(RevitVersion)</DefineConstants>
  </PropertyGroup>
  <!--debug action,for revit version < 2019, use "debug-attach to process" to debug -->
  <PropertyGroup Condition=" '$(Configuration)' != 'Release' ">
    <StartAction Condition="$(RevitVersion) &lt;= '2018'">Project</StartAction>
    <StartAction Condition="$(RevitVersion) &gt;'2018'">Program</StartAction>
    <StartProgram Condition="$(RevitVersion)&gt;'2018'"
      >C:/Program Files/Autodesk/Revit $(RevitVersion)/Revit.exe</StartProgram
    >
  </PropertyGroup>
  <!--TargetFramework-->
  <PropertyGroup>
    <TargetFramework Condition="$(RevitVersion) &lt;= '2024'">net48</TargetFramework>
    <TargetFramework Condition="$(RevitVersion) == '2025'">net8.0-windows</TargetFramework>
  </PropertyGroup>
  <!--output path-->
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <IntermediateOutputPath>$(SolutionDir)obj/$(MSBuildProjectName)/revit$(RevitVersion)/</IntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(SolutionDir)obj/$(MSBuildProjectName)/revit$(RevitVersion)/</MSBuildProjectExtensionsPath>
    <OutputPath>$(SolutionDir)bin/$(MSBuildProjectName)/revit$(RevitVersion)/</OutputPath>
  </PropertyGroup>
  <!--packages-->
  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="NLog" Version="6.0.3" />
  </ItemGroup>
  <!--analyser-->
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)external/pyxis/csharp/src/Pyxis/Pyxis.csproj" />
    <PackageReference Include="CSharpier.MsBuild" Version="1.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="4.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
