<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <!--set
  debug revit version and constants-->
  <PropertyGroup Condition="$(Configuration.StartsWith('Debug'))">
    <RevitVersion>$(Configuration.Replace("Debug",""))</RevitVersion>
    <DefineConstants>$(DefineConstants);Debug</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration)=='Release'">
    <DefineConstants>$(DefineConstants);Release</DefineConstants>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <!--output
  path-->
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <IntermediateOutputPath>$(SolutionDir)obj/$(MSBuildProjectName)/revit$(RevitVersion)/</IntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(SolutionDir)obj/$(MSBuildProjectName)/revit$(RevitVersion)/</MSBuildProjectExtensionsPath>
    <OutputPath>$(SolutionDir)bin/$(MSBuildProjectName)/revit$(RevitVersion)/</OutputPath>
  </PropertyGroup>
  <!--packages-->
  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="ZLinq" Version="1.5.2" />
  </ItemGroup>
</Project>
