name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: build
        run: ./scripts/build.ps1

      # upload
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Mason
          path: bin/**
          if-no-files-found: error

      # test
      - run: ./scripts/test.ps1
      - uses: Glatzel/template/.github/actions/common/codecov@0ac17bbcfdbe5322e88667b2a7079f8044c10e84 # v2026.8.27
        if: ${{!cancelled()}}
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, build]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
