name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: build
        run: ./scripts/build.ps1

      # upload
      - uses: actions/upload-artifact@v7
        with:
          name: Mason
          path: bin/**
          if-no-files-found: error

      # test
      - run: ./scripts/test.ps1
      - uses: ./.github/actions/common/codecov
        if: ${{ !cancelled() }}
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook,build]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
