name: release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  contents: write

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      upload: true

  get-tag:
    runs-on: windows-latest
    outputs:
      tag: ${{ steps.main.outputs.tag }}
      is_pre_release: ${{ steps.main.outputs.is_pre_release }}
    steps:
      - uses: actions/checkout@v4

      - name: get-tag
        id: main
        run: |
          # get version in Directory.Build.props
          $projdata = [xml](Get-Content "./src/Directory.Build.props")
          $version=$projdata.Project.PropertyGroup.Version
          $version="$version".Replace(" ","")
          Write-Output "Directory.Build.props version: v$version"

          # set tag
          $tag="v$version"
          Write-Output "tag: $tag"
          "tag=$tag" >> "$env:GITHUB_OUTPUT"

  release:
    needs: [build, get-tag]
    uses: Glatzel/template/.github/workflows/release.yml@main
    with:
      override: true
      tag: ${{needs.get-tag.outputs.tag}}
      have_changelog: true
      assets: Mason